apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: opencodequest-quarkus-with-AI
  title: "OpenCodeQuest - AI-Infused application with Quarkus"
  description: "Create a quarkus intelligent application"
  tags:
    - fight-service
    - java
    - quarkus
    - opencodequest
    - ai
    - intelligent
spec:
  owner: rhdh
  type: service
  parameters:
    - title: Provide information about the OpenShift cluster
      required:
        - openshiftCluster
        - image_host
        - image_organization
        - image_tag
      properties:
        openshiftCluster:
          title: OpenShift Clusters
          type: string
          enum:
            - {{ openshift_apps_domain }}
          default: {{ openshift_apps_domain }}
      dependencies:
        openshiftCluster:
          oneOf:
            - properties:
                openshiftCluster:
                  enum:
                    - {{ openshift_apps_domain }}
                  default: {{ openshift_apps_domain }}
                image_host:
                  title: Image Host
                  type: string
                  description: Host for storing image
                  enum: 
                    - quay.{{ openshift_apps_domain }}
                  default: quay.{{ openshift_apps_domain }}
                image_organization:
                  title: Organization
                  type: string
                  description: Name of the Quay Organization
                  ui:field: EntityPicker
                  ui:options:
                    showOnlyUserOwnGroups: true
                    allowArbitraryValues: false
                    allowedKinds:
                      - Group
                image_tag:
                  title: Image Tag
                  default: latest
                  type: string
                  description: Build Image tag

    - title: Provide Information for Application
      required:
        - component_id
        - java_package_name
        - api_endpoint
        - group_id
        - artifact_id
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component ("fight" is good starting point)
          default: fight
          ui:field: EntityNamePicker
          maxLength: 23
        group_id:
          title: Group Id
          type: string
          default: com.redhat.workshop
          description: Maven Group Id
        artifact_id:
          title: Artifact Id
          type: string
          default: fight-service
          description: Maven Artifact Id
        java_package_name:
          title: Java Package Name
          type: string
          description: Name for the java package. eg (com.redhat.blah)
          default: io.quarkus.workshop.fight
        api_endpoint:
          title: API Endpoint
          default: /api/fight
          type: string
          description: Path of the first API Endpoint
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
          default: My super fight service

  steps:

    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutTemplating:
          - .github/workflows/*
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          namespace: '${{ user.entity.metadata.name }}-workshop-dev'
          group_id: ${{ parameters.group_id }}
          artifact_id: ${{ parameters.artifact_id }}
          java_package_name: ${{ parameters.java_package_name }}
          java_package_name_dir: ${{ parameters.java_package_name | replace(".","/") }}
          owner: ${{ user.entity.metadata.name }}_org
          cluster: .${{ parameters.openshiftCluster }}
          host: ${{ parameters.repo.host }}.${{ parameters.openshiftCluster }}
          destination: '${{ user.entity.metadata.name }}_org/${{ parameters.component_id }}/src/branch/main/'
          quay_destination: ${{ parameters.image_organization}}/${{ user.entity.metadata.name }}-${{ parameters.component_id }}
          port: 8080
          verify_commits: enabled
          api_endpoint: ${{ parameters.api_endpoint }}
          system: ${{ user.entity.metadata.name }}-workshop
          user: ${{ user.entity.metadata.name }}

    - id: publish
      name: Publish
      action: publish:gitea
      input:
        repoUrl: "gitea-gitea.${{ parameters.openshiftCluster }}?owner=${{ user.entity.metadata.name }}_org&repo=${{parameters.component_id}}"
        repoVisibility: public
        description: "Open Code Quest Quarkus AI"

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /main/catalog-info.yaml

    - id: template-gitops-deployment
      name: Generating Deployment Resources
      action: fetch:template
      input:
        url: ./manifests
        copyWithoutTemplating: []
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          destination: https://gitea-gitea.${{ parameters.openshiftCluster }}/${{ user.entity.metadata.name }}/${{parameters.component_id}}-gitops.git
          source_repository: https://gitea-gitea.${{ parameters.openshiftCluster }}/${{ user.entity.metadata.name }}/${{parameters.component_id}}.git
          repository_name: ${{parameters.component_id}}
          git_owner: '${{ user.entity.metadata.name }}'
          cluster: .${{ parameters.openshiftCluster }}
          namespace: ${{ user.entity.metadata.name }}-workshop-dev
          image_registry: ${{ parameters.image_registry }}
          image_host: ${{ parameters.image_host }}
          image_organization: ${{ parameters.image_organization }}
          image_name: ${{ parameters.component_id }}
          image_tag: ${{ parameters.image_tag }}
          port: 8080
          repository_host: gitea-gitea.${{ parameters.openshiftCluster }}
          deployment_name: ${{ parameters.component_id }}
          user: ${{ user.entity.metadata.name }}
          verify_commits: enabled
        targetPath: ./tenant-gitops

    - id: publish-gitops
      name: Publishing to Resource Repository
      action: publish:gitea
      input:
        repoUrl: "gitea-gitea.${{ parameters.openshiftCluster }}?owner=${{ user.entity.metadata.name }}_org&repo=${{parameters.component_id}}-gitops"
        sourcePath: ./tenant-gitops
        repoVisibility: public
        description: "Open Code Quest Quarkus AI Deployment Resource"

    - id: create-argocd-resources
      name: Create ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: ${{ user.entity.metadata.name }}-${{ parameters.component_id }}-bootstrap
        argoInstance: openshift-gitops
        namespace: ${{ user.entity.metadata.name }}-workshop
        repoUrl: 'https://gitea-gitea.${{ parameters.openshiftCluster }}/${{ user.entity.metadata.name }}_org/${{ parameters.component_id }}-gitops.git'
        path: 'argocd/'

  output:
    links:
      - title: Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open Component in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
